package cep;

import com.ftn.sbnz.model.Tournament;

 query isContainedIn(String x, String y)
    Tournament(x, y; )
    or
    (Tournament(z, y; ) and isContainedIn(x, z;))
end

rule "Svi Osvajaci kopenhagena"
    when
        $s : String( this == "1")
        isContainedIn("Copenhagen 2022", ime; )
    then
        System.out.println( "Tim " + ime + " je osvojio Copenhagen 2022" );

end


rule "Teams that won Major tournaments"
    when
        $s : String( this == "1")
        isContainedIn("G2", ime; )
    then
        System.out.println( "Tim " + ime + " je osvojio Copenhagen 2022" );
end