package cep;

import com.ftn.sbnz.model.HeadshotKillEvent
import com.ftn.sbnz.model.UtilityUsageEvent
import com.ftn.sbnz.model.WallbangEvent
import com.ftn.sbnz.model.GameStatistic
import com.ftn.sbnz.model.ReportCooldown
import com.ftn.sbnz.model.enums.Report



rule "AIMBOT Headshot Kill Rule"
no-loop
when
    $event: HeadshotKillEvent($gameStatId: gameStatisticId)
    $statistic: GameStatistic(id == $gameStatId)
    exists(not ReportCooldown(gameStatisticId == $gameStatId) over window: time(1m))
    Number(intValue >= 5) from accumulate(
        HeadshotKillEvent(gameStatisticId == $gameStatId) over window:time(5m),
        count()
    )
then
    System.out.println("AIMBOT Headshot Kill Rule activated! 1");
    insert(new ReportCooldown($gameStatId));
end

rule "AIMBOT Headshot and Utility Usage Rule"
when
    $headshotEvent: HeadshotKillEvent($gameStatId: gameStatisticId)
    $statistic: GameStatistic(id == $gameStatId)
    Number(intValue >= 3) from accumulate(
        HeadshotKillEvent(gameStatisticId == $gameStatId) over window:time(5m),
        count()
    )
    Number(intValue >= 5) from accumulate(
        UtilityUsageEvent(gameStatisticId == $gameStatId) over window:time(2m),
        count()
    )
then
    // Trigger AIMBOT report
    $statistic.getReports().add(Report.AIMBOT);
    System.out.println("AIMBOT Headshot Kill Rule activated! 2");
    update($statistic);
end

rule "WALLHACK Wallbang Kill Rule"
when
    $wallbangEvent: WallbangEvent($gameStatId: gameStatisticId)
    $statistic: GameStatistic(id == $gameStatId)
     Number(intValue >= 5) from accumulate(
        WallbangEvent(gameStatisticId == $gameStatId) over window:time(5m),
        count()
    )
then
    // Trigger WALLHACK report
    $statistic.getReports().add(Report.WALLHACK);
        System.out.println("AIMBOT Headshot Kill Rule activated! 3");
    update($statistic);
end