package cep;
import com.ftn.sbnz.model.GameStatistic
import com.ftn.sbnz.model.Game

import com.ftn.sbnz.model.User;
import com.ftn.sbnz.model.enums.UserType;

query getAllUsersNotAdmin
    $user : User(userType != UserType.ADMIN)

end

query UserActiveGameStatistics(Long userIdParam)
    $game : Game(isEnded == false)
    $gameStatistic : GameStatistic(userId == userIdParam) from $game.gameStatistics
end

